title: Портфолио Говоров А.С.
description: Портфолио системного аналитика
baseurl: "/portfolio"
url: "https://govorov07.github.io"

# Включить обработку 404
permalink: pretty

# Настройки для SPA
include: [".htaccess"]